name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 10
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 9, 10, 11]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Setup jFastBPE
      run: git clone git@github.com:mitre/jfastbpe.git && cd jfastbpe && gradle test build jar publishToMavenLocal
    - name: Setup sentencepiece-jni on Windows
      run: git clone git@github.com:levyfan/sentencepiece-jni.git && cd sentencepiece-jni && mvn -f pom-windows.xml clean install
      if: matrix.os == 'windows-latest'
    - name: Setup sentencepiece-jni on non-Windows
      run: git clone git@github.com:levyfan/sentencepiece-jni.git && cd sentencepiece-jni && mvn -f pom.xml clean install
      if: matrix.os != 'windows-latest'
    - name: Build
      run: gradle test build jar
